# Generated by Django 2.2.13 on 2020-06-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ghvhggfgvcafvwse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='caasdc',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='sacscs',
        ),
    ]
