# Generated by Django 2.2.13 on 2020-06-13 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0005_auto_20200613_0719"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="ftghryuj5y",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customtext_ftghryuj5y",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customtext",
            name="sfasdfasz",
            field=models.ManyToManyField(
                blank=True, related_name="customtext_sfasdfasz", to="home.HomePage"
            ),
        ),
    ]
